stages:
  - build
  - test
  - release
  - deploy

variables:
  APPLICATION_NAME: group-manager
  CONTAINER_REGISTRY: ${AWS_ECR_PUBLIC_URL}
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TEST: ${CONTAINER_IMAGE}:test
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    # Create repository in ECR if it does not exist yet
    - >
      aws ecr-public create-repository --region us-east-1 --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"
  script:
    - docker build --build-arg APP_VERSION=${CI_COMMIT_TAG} -t ${CONTAINER_IMAGE_TEST} .
    - docker push ${CONTAINER_IMAGE_TEST}

test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    # Creating network for TDD
    - docker network create tdd
    # Creating DB container in network
    - >
      docker run
      -d
      --rm
      --name tdd-db
      --network tdd
      --hostname tdd-db
      --env NEO4J_AUTH=none
      neo4j:5.12.0
    - sleep 30 # Wait for Neo4J to become available
    - >
      docker run
      -d
      --rm
      --name tdd-user-manager
      --network tdd
      --hostname tdd-user-manager
      --env NEO4J_URL=bolt://tdd-db
      --env JWT_SECRET=keyboardcat
      moreillon/user-manager:v4.5.3
    - sleep 10 # Wait for User manager to become available
  script:
    - >
      docker run
      --rm
      --name tdd-app
      --network tdd
      --env NEO4J_URL=bolt://tdd-db
      --env IDENTIFICATION_URL=http://tdd-user-manager/users/self
      --env LOGIN_URL=http://tdd-user-manager/auth/login
      --env TEST_USER_USERNAME=admin
      --env TEST_USER_PASSWORD=admin
      ${CONTAINER_IMAGE_TEST}
      npm run coverage

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - docker pull ${CONTAINER_IMAGE_TEST}
    # Tagging
    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_TAGGED}
    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_LATEST}
    # Pushing
    - docker push ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE_LATEST}

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - kubectl config use-context eks/gitlab-agent-for-kubernetes:eks
    - kubectl config set-context --current --namespace=moreillon
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
